### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by samccone** [samccone/headless-snap#1]
- [ ] scripting interface wrapper
- [ ] configure window size
- [ ] Phantomjs API interop 

more :goat:

**Comment by zackarychapple** [comment]
This is awesome! Some ideas
- [ ] Typescript classes / @types definition
- [ ] Time Delay
- [ ] Devtools overlay (size, file count, time to load etc)
